Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 235, in main
    macrobatch=args.macrobatch)
  File "../sgd.py", line 23, in __init__
    macrobatch=macrobatch,
  File "../optimizer.py", line 41, in __init__
    master_parameters, **optimizer_args)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/optim/sgd.py", line 64, in __init__
    super(SGD, self).__init__(params, defaults)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/optim/optimizer.py", line 45, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 235, in main
    macrobatch=args.macrobatch)
  File "../sgd.py", line 23, in __init__
    macrobatch=macrobatch,
  File "../optimizer.py", line 41, in __init__
    master_parameters, **optimizer_args)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/optim/sgd.py", line 64, in __init__
    super(SGD, self).__init__(params, defaults)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/optim/optimizer.py", line 45, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../communication.py", line 484, in send_and_recv_helper_thread
    dist.barrier(sub_process_group)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1194, in barrier
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [10.0.6.249]:18836
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../communication.py", line 464, in send_and_recv_helper_thread
    dist.barrier(sub_process_group)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1194, in barrier
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [10.0.6.249]:10644


Exception in thread Thread-22:
Traceback (most recent call last):
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../communication.py", line 464, in send_and_recv_helper_thread
    dist.barrier(sub_process_group)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1194, in barrier
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [10.0.6.249]:9868
Exception in thread Thread-22:
Traceback (most recent call last):
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../communication.py", line 464, in send_and_recv_helper_thread
    dist.barrier(sub_process_group)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1194, in barrier
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [10.0.6.249]:29318


Exception in thread Thread-22:
Traceback (most recent call last):
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../communication.py", line 464, in send_and_recv_helper_thread
    dist.barrier(sub_process_group)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1194, in barrier
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [10.0.6.249]:44197

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../communication.py", line 464, in send_and_recv_helper_thread
    dist.barrier(sub_process_group)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1194, in barrier
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [10.0.6.249]:654

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../communication.py", line 464, in send_and_recv_helper_thread
    dist.barrier(sub_process_group)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1194, in barrier
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [10.0.6.249]:24236

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../communication.py", line 464, in send_and_recv_helper_thread
    dist.barrier(sub_process_group)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1194, in barrier
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [10.0.6.249]:27265

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../communication.py", line 464, in send_and_recv_helper_thread
    dist.barrier(sub_process_group)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1194, in barrier
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [10.0.6.249]:37513

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../communication.py", line 484, in send_and_recv_helper_thread
    dist.barrier(sub_process_group)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1194, in barrier
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [10.0.6.249]:9946

Traceback (most recent call last):
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/launch.py", line 173, in <module>
    main()
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/launch.py", line 169, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/bin/python3', '-u', 'main_with_runtime.py', '--rank=31', '--local_rank=3', '-s', '--distributed_backend', 'gloo', '-m', 'models.alexnet.gpus=8_4_theory', '--epochs', '6', '-b', '256', '--config_path', 'models/alexnet/gpus=8_4_theory/hybrid_conf.json', '--num_ranks_in_server', '4', '--master_addr', '10.0.6.209']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    main()
  File "main_with_runtime.py", line 332, in main
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 0; 15.90 GiB total capacity; 14.66 GiB already allocated; 67.31 MiB free; 537.37 MiB cached)
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 2; 15.90 GiB total capacity; 14.71 GiB already allocated; 35.38 MiB free; 537.13 MiB cached)
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 0; 15.90 GiB total capacity; 14.71 GiB already allocated; 35.38 MiB free; 537.13 MiB cached)
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 1; 15.90 GiB total capacity; 14.71 GiB already allocated; 35.38 MiB free; 537.13 MiB cached)
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 3; 15.90 GiB total capacity; 14.71 GiB already allocated; 35.38 MiB free; 537.13 MiB cached)
Traceback (most recent call last):
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    train(train_loader, r, optimizer, epoch)
    r.run_forward()
  File "main_with_runtime.py", line 396, in train
  File "../runtime.py", line 523, in run_forward
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 2; 15.90 GiB total capacity; 14.71 GiB already allocated; 30.50 MiB free; 537.13 MiB cached)
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 0; 15.90 GiB total capacity; 14.71 GiB already allocated; 27.38 MiB free; 537.13 MiB cached)
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 1; 15.90 GiB total capacity; 14.66 GiB already allocated; 69.38 MiB free; 537.37 MiB cached)
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 3; 15.90 GiB total capacity; 14.71 GiB already allocated; 27.38 MiB free; 537.13 MiB cached)
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 1; 15.90 GiB total capacity; 14.71 GiB already allocated; 35.38 MiB free; 537.13 MiB cached)
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 0; 15.90 GiB total capacity; 14.71 GiB already allocated; 35.38 MiB free; 537.13 MiB cached)
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 3; 15.90 GiB total capacity; 14.71 GiB already allocated; 27.38 MiB free; 537.13 MiB cached)
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 0; 15.90 GiB total capacity; 14.66 GiB already allocated; 77.38 MiB free; 537.37 MiB cached)
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 3; 15.90 GiB total capacity; 14.71 GiB already allocated; 35.38 MiB free; 537.13 MiB cached)
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 2; 15.90 GiB total capacity; 14.66 GiB already allocated; 77.38 MiB free; 537.37 MiB cached)
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 1; 15.90 GiB total capacity; 14.66 GiB already allocated; 49.31 MiB free; 537.37 MiB cached)
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 2; 15.90 GiB total capacity; 14.66 GiB already allocated; 69.38 MiB free; 537.37 MiB cached)
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
Traceback (most recent call last):
  File "main_with_runtime.py", line 332, in main
  File "main_with_runtime.py", line 627, in <module>
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    main()
  File "main_with_runtime.py", line 332, in main
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 2; 15.90 GiB total capacity; 14.71 GiB already allocated; 5.38 MiB free; 537.13 MiB cached)
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 3; 15.90 GiB total capacity; 14.71 GiB already allocated; 35.38 MiB free; 537.13 MiB cached)
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 1; 15.90 GiB total capacity; 14.71 GiB already allocated; 7.38 MiB free; 537.13 MiB cached)
Traceback (most recent call last):
  File "main_with_runtime.py", line 627, in <module>
    main()
  File "main_with_runtime.py", line 332, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 396, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/sendandrecv/image_classification/models/alexnet/gpus=8_4_theory/stage0.py", line 23, in forward
    out4 = self.layer4(out3)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 146, in forward
    self.return_indices)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 490, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 482, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 0; 15.90 GiB total capacity; 14.71 GiB already allocated; 3.38 MiB free; 539.12 MiB cached)
