Traceback (most recent call last):
  File "main_with_runtime.py", line 626, in <module>
Traceback (most recent call last):
  File "main_with_runtime.py", line 626, in <module>
Traceback (most recent call last):
  File "main_with_runtime.py", line 626, in <module>
Traceback (most recent call last):
  File "main_with_runtime.py", line 626, in <module>
    main()
  File "main_with_runtime.py", line 331, in main
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 391, in train
    main()
  File "main_with_runtime.py", line 331, in main
    main()
  File "main_with_runtime.py", line 331, in main
    main()
  File "main_with_runtime.py", line 331, in main
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 391, in train
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 391, in train
    train(train_loader, r, optimizer, epoch)
  File "main_with_runtime.py", line 391, in train
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    r.run_forward()
  File "../runtime.py", line 523, in run_forward
    self._run_forward(tensors)
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
  File "../runtime.py", line 571, in _run_forward
    self._run_forward(tensors)
  File "../runtime.py", line 571, in _run_forward
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    for input_name in input_names])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
    result = self.forward(*input, **kwargs)
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 368, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    return self.module(*inputs[0], **kwargs[0])
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/improve/image_classification/models/resnet50/gpus=2_4_theory/stage0.py", line 115, in forward
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/improve/image_classification/models/resnet50/gpus=2_4_theory/stage0.py", line 107, in forward
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/improve/image_classification/models/resnet50/gpus=2_4_theory/stage0.py", line 115, in forward
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/pipedream/improve/image_classification/models/resnet50/gpus=2_4_theory/stage0.py", line 107, in forward
    out34 = self.layer34(out33)
    out25 = out25 + out17
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    out34 = self.layer34(out33)
RuntimeError: CUDA out of memory. Tried to allocate 98.00 MiB (GPU 2; 15.90 GiB total capacity; 14.87 GiB already allocated; 87.38 MiB free; 315.93 MiB cached)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    out25 = out25 + out17
RuntimeError: CUDA out of memory. Tried to allocate 98.00 MiB (GPU 3; 15.90 GiB total capacity; 14.87 GiB already allocated; 53.38 MiB free; 317.93 MiB cached)
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 339, in forward
    result = self.forward(*input, **kwargs)
  File "/home/6/17B13541/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 339, in forward
    self.padding, self.dilation, self.groups)
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 98.00 MiB (GPU 0; 15.90 GiB total capacity; 14.98 GiB already allocated; 73.31 MiB free; 220.93 MiB cached)
RuntimeError: CUDA out of memory. Tried to allocate 98.00 MiB (GPU 1; 15.90 GiB total capacity; 15.02 GiB already allocated; 35.38 MiB free; 221.18 MiB cached)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../communication.py", line 534, in recv_helper_thread
    sub_process_group=sub_process_group)
  File "../communication.py", line 654, in _recv_async
    tensor = torch.zeros(received_tensor_shape, dtype=dtype).cuda()
RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 15.90 GiB total capacity; 15.04 GiB already allocated; 9.31 MiB free; 222.68 MiB cached)

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../communication.py", line 534, in recv_helper_thread
    sub_process_group=sub_process_group)
  File "../communication.py", line 654, in _recv_async
    tensor = torch.zeros(received_tensor_shape, dtype=dtype).cuda()
RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 1; 15.90 GiB total capacity; 15.04 GiB already allocated; 9.38 MiB free; 222.68 MiB cached)

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../communication.py", line 534, in recv_helper_thread
    sub_process_group=sub_process_group)
  File "../communication.py", line 654, in _recv_async
    tensor = torch.zeros(received_tensor_shape, dtype=dtype).cuda()
RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 2; 15.90 GiB total capacity; 14.93 GiB already allocated; 23.38 MiB free; 317.68 MiB cached)

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/t3/sles12sp4/free/python/3.6.5/gcc4.8.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../communication.py", line 534, in recv_helper_thread
    sub_process_group=sub_process_group)
  File "../communication.py", line 654, in _recv_async
    tensor = torch.zeros(received_tensor_shape, dtype=dtype).cuda()
RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 3; 15.90 GiB total capacity; 14.93 GiB already allocated; 5.38 MiB free; 317.68 MiB cached)

